version: '3.7'

services:
  database:
    image: mariadb
    restart: always
    container_name: social-web-db
    ports:
      - 4000:3306
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=social-web-db
  
  backend:
    image: social-media-site-backend
    restart: always
    container_name: social-media-site-backend
    depends_on:
      - "database"
    ports:
      - 8000:9000
