version: '3.7'

services:
  database:
    image: mariadb
    restart: always
    container_name: social-web-db
    ports:
      - 4000:3306
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_DATABASE=
  
  backend:
    image: social-media-site-backend
    restart: always
    container_name: social-media-site-backend
    depends_on:
      - "database"
    ports:
      - 8000:9000
    environment:
      - DATABASE_DIALECT=
      - DATABASE_DRIVER=
      - DATABASE_USERNAME=
      - DATABASE_PASSWORD=
      - DATABASE_HOST=
      - DATABASE_PORT=
      - DATABASE_DBNAME=
      - SECRET_KEY=
      - ALGORITHM=
      - ACCESS_TOKEN_EXPIRE_MINUTES=